/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InventoryItem {
    maxStock: bigint;
    sellPrice: bigint;
    minStock: bigint;
    stock: bigint;
    itemCode: string;
    buyPrice: bigint;
    itemName: string;
    quantity: bigint;
}
export interface CustomerRecord {
    discountAmount: bigint;
    name: string;
    discountType: DiscountType;
    phone: string;
    discountPercentage: bigint;
    vehicleHistory: Array<VehicleHistory>;
    transactionCount: bigint;
}
export interface VehicleHistory {
    model: string;
    brand: string;
    plate: string;
}
export interface TransactionItem {
    sellPrice: bigint;
    itemCode: string;
    buyPrice: bigint;
    quantity: bigint;
}
export interface ServiceRecord {
    id: bigint;
    customerName: string;
    status: Status;
    vehicleBrand: string;
    technicianName: string;
    repairAction?: string;
    vehicleModel: string;
    plateNumber?: string;
    problemDescription: string;
}
export interface UserProfile {
    name: string;
    email?: string;
}
export interface Transaction {
    id: bigint;
    customerName: string;
    customerPhone: string;
    buyPrices: Array<[string, bigint]>;
    totalAmount: bigint;
    items: Array<TransactionItem>;
}
export enum DiscountType {
    goods = "goods",
    services = "services"
}
export enum Status {
    masuk = "masuk",
    selesai = "selesai"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdateInventoryItem(item: InventoryItem): Promise<void>;
    addServiceRecord(record: ServiceRecord): Promise<bigint>;
    addTransaction(transaction: Transaction): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCustomerRecord(phone: string): Promise<void>;
    deleteInventoryItem(itemCode: string): Promise<void>;
    deleteServiceRecord(id: bigint): Promise<void>;
    deleteTransaction(id: bigint): Promise<void>;
    findCustomersByName(searchTerm: string): Promise<Array<CustomerRecord>>;
    getAllCustomers(): Promise<Array<CustomerRecord>>;
    getAllInventoryItems(): Promise<Array<InventoryItem>>;
    getAllServiceRecords(): Promise<Array<ServiceRecord>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerRecord(phone: string): Promise<CustomerRecord | null>;
    getInventoryItem(itemCode: string): Promise<InventoryItem | null>;
    getProfitLossReport(startDate: bigint, endDate: bigint): Promise<{
        grossProfit: bigint;
        totalCostOfGoodsSold: bigint;
        itemizedSales: Array<[string, bigint]>;
        totalRevenue: bigint;
    }>;
    getServiceQueue(): Promise<Array<ServiceRecord>>;
    getServiceRecord(id: bigint): Promise<ServiceRecord | null>;
    getTransaction(id: bigint): Promise<Transaction | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateServiceStatus(id: bigint, status: Status, repairAction: string | null): Promise<void>;
    upsertCustomerRecord(record: CustomerRecord): Promise<void>;
}
import type { CustomerRecord as _CustomerRecord, DiscountType as _DiscountType, InventoryItem as _InventoryItem, ServiceRecord as _ServiceRecord, Status as _Status, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole, VehicleHistory as _VehicleHistory } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdateInventoryItem(arg0: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateInventoryItem(arg0);
            return result;
        }
    }
    async addServiceRecord(arg0: ServiceRecord): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addServiceRecord(to_candid_ServiceRecord_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addServiceRecord(to_candid_ServiceRecord_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTransaction(arg0: Transaction): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCustomerRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomerRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomerRecord(arg0);
            return result;
        }
    }
    async deleteInventoryItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventoryItem(arg0);
            return result;
        }
    }
    async deleteServiceRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteServiceRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteServiceRecord(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async findCustomersByName(arg0: string): Promise<Array<CustomerRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.findCustomersByName(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findCustomersByName(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCustomers(): Promise<Array<CustomerRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInventoryItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInventoryItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInventoryItems();
            return result;
        }
    }
    async getAllServiceRecords(): Promise<Array<ServiceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServiceRecords();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServiceRecords();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerRecord(arg0: string): Promise<CustomerRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerRecord(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerRecord(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryItem(arg0: string): Promise<InventoryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItem(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItem(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfitLossReport(arg0: bigint, arg1: bigint): Promise<{
        grossProfit: bigint;
        totalCostOfGoodsSold: bigint;
        itemizedSales: Array<[string, bigint]>;
        totalRevenue: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfitLossReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfitLossReport(arg0, arg1);
            return result;
        }
    }
    async getServiceQueue(): Promise<Array<ServiceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceQueue();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceQueue();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceRecord(arg0: bigint): Promise<ServiceRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceRecord(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceRecord(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransaction(arg0: bigint): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateServiceStatus(arg0: bigint, arg1: Status, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceStatus(arg0, to_candid_Status_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceStatus(arg0, to_candid_Status_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async upsertCustomerRecord(arg0: CustomerRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertCustomerRecord(to_candid_CustomerRecord_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertCustomerRecord(to_candid_CustomerRecord_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CustomerRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerRecord): CustomerRecord {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_DiscountType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscountType): DiscountType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceRecord_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceRecord): ServiceRecord {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerRecord]): CustomerRecord | null {
    return value.length === 0 ? null : from_candid_CustomerRecord_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InventoryItem]): InventoryItem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceRecord]): ServiceRecord | null {
    return value.length === 0 ? null : from_candid_ServiceRecord_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _Status;
    vehicleBrand: string;
    technicianName: string;
    repairAction: [] | [string];
    vehicleModel: string;
    plateNumber: [] | [string];
    problemDescription: string;
}): {
    id: bigint;
    customerName: string;
    status: Status;
    vehicleBrand: string;
    technicianName: string;
    repairAction?: string;
    vehicleModel: string;
    plateNumber?: string;
    problemDescription: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_Status_n15(_uploadFile, _downloadFile, value.status),
        vehicleBrand: value.vehicleBrand,
        technicianName: value.technicianName,
        repairAction: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.repairAction)),
        vehicleModel: value.vehicleModel,
        plateNumber: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.plateNumber)),
        problemDescription: value.problemDescription
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
}): {
    name: string;
    email?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    discountAmount: bigint;
    name: string;
    discountType: _DiscountType;
    phone: string;
    discountPercentage: bigint;
    vehicleHistory: Array<_VehicleHistory>;
    transactionCount: bigint;
}): {
    discountAmount: bigint;
    name: string;
    discountType: DiscountType;
    phone: string;
    discountPercentage: bigint;
    vehicleHistory: Array<VehicleHistory>;
    transactionCount: bigint;
} {
    return {
        discountAmount: value.discountAmount,
        name: value.name,
        discountType: from_candid_DiscountType_n10(_uploadFile, _downloadFile, value.discountType),
        phone: value.phone,
        discountPercentage: value.discountPercentage,
        vehicleHistory: value.vehicleHistory,
        transactionCount: value.transactionCount
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goods: null;
} | {
    services: null;
}): DiscountType {
    return "goods" in value ? DiscountType.goods : "services" in value ? DiscountType.services : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    masuk: null;
} | {
    selesai: null;
}): Status {
    return "masuk" in value ? Status.masuk : "selesai" in value ? Status.selesai : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceRecord>): Array<ServiceRecord> {
    return value.map((x)=>from_candid_ServiceRecord_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerRecord>): Array<CustomerRecord> {
    return value.map((x)=>from_candid_CustomerRecord_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CustomerRecord_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerRecord): _CustomerRecord {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_DiscountType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): _DiscountType {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceRecord): _ServiceRecord {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: Status;
    vehicleBrand: string;
    technicianName: string;
    repairAction?: string;
    vehicleModel: string;
    plateNumber?: string;
    problemDescription: string;
}): {
    id: bigint;
    customerName: string;
    status: _Status;
    vehicleBrand: string;
    technicianName: string;
    repairAction: [] | [string];
    vehicleModel: string;
    plateNumber: [] | [string];
    problemDescription: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: to_candid_Status_n3(_uploadFile, _downloadFile, value.status),
        vehicleBrand: value.vehicleBrand,
        technicianName: value.technicianName,
        repairAction: value.repairAction ? candid_some(value.repairAction) : candid_none(),
        vehicleModel: value.vehicleModel,
        plateNumber: value.plateNumber ? candid_some(value.plateNumber) : candid_none(),
        problemDescription: value.problemDescription
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
}): {
    name: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    discountAmount: bigint;
    name: string;
    discountType: DiscountType;
    phone: string;
    discountPercentage: bigint;
    vehicleHistory: Array<VehicleHistory>;
    transactionCount: bigint;
}): {
    discountAmount: bigint;
    name: string;
    discountType: _DiscountType;
    phone: string;
    discountPercentage: bigint;
    vehicleHistory: Array<_VehicleHistory>;
    transactionCount: bigint;
} {
    return {
        discountAmount: value.discountAmount,
        name: value.name,
        discountType: to_candid_DiscountType_n32(_uploadFile, _downloadFile, value.discountType),
        phone: value.phone,
        discountPercentage: value.discountPercentage,
        vehicleHistory: value.vehicleHistory,
        transactionCount: value.transactionCount
    };
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): {
    goods: null;
} | {
    services: null;
} {
    return value == DiscountType.goods ? {
        goods: null
    } : value == DiscountType.services ? {
        services: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    masuk: null;
} | {
    selesai: null;
} {
    return value == Status.masuk ? {
        masuk: null
    } : value == Status.selesai ? {
        selesai: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
