/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerRecord {
  'discountAmount' : bigint,
  'name' : string,
  'discountType' : DiscountType,
  'phone' : string,
  'discountPercentage' : bigint,
  'vehicleHistory' : Array<VehicleHistory>,
  'transactionCount' : bigint,
}
export type DiscountType = { 'goods' : null } |
  { 'services' : null };
export interface InventoryItem {
  'maxStock' : bigint,
  'type' : InventoryType,
  'sellPrice' : bigint,
  'minStock' : bigint,
  'stock' : [] | [bigint],
  'itemCode' : string,
  'buyPrice' : bigint,
  'itemName' : string,
  'quantity' : [] | [bigint],
}
export type InventoryType = { 'jasa' : null } |
  { 'barang' : null };
export interface ServiceRecord {
  'id' : bigint,
  'customerName' : string,
  'status' : Status,
  'vehicleBrand' : string,
  'technicianName' : string,
  'repairAction' : [] | [string],
  'vehicleModel' : string,
  'plateNumber' : [] | [string],
  'problemDescription' : string,
}
export type Status = { 'masuk' : null } |
  { 'selesai' : null };
export interface Transaction {
  'id' : bigint,
  'customerName' : string,
  'customerPhone' : string,
  'buyPrices' : Array<[string, bigint]>,
  'totalAmount' : bigint,
  'items' : Array<TransactionItem>,
}
export interface TransactionItem {
  'sellPrice' : bigint,
  'itemCode' : string,
  'buyPrice' : bigint,
  'quantity' : bigint,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VehicleHistory {
  'model' : string,
  'brand' : string,
  'plate' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addInventoryItem' : ActorMethod<[InventoryItem], undefined>,
  'addServiceRecord' : ActorMethod<[ServiceRecord], bigint>,
  'addTransaction' : ActorMethod<[Transaction], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCustomerRecord' : ActorMethod<[string], undefined>,
  'deleteInventoryItem' : ActorMethod<[string], undefined>,
  'deleteServiceRecord' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'findCustomersByName' : ActorMethod<[string], Array<CustomerRecord>>,
  'getAllCustomers' : ActorMethod<[], Array<CustomerRecord>>,
  'getAllInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getAllServiceRecords' : ActorMethod<[], Array<ServiceRecord>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerRecord' : ActorMethod<[string], [] | [CustomerRecord]>,
  'getInventoryItem' : ActorMethod<[string], [] | [InventoryItem]>,
  'getProfitLossReport' : ActorMethod<
    [bigint, bigint],
    {
      'grossProfit' : bigint,
      'totalCostOfGoodsSold' : bigint,
      'itemizedSales' : Array<[string, bigint]>,
      'totalRevenue' : bigint,
    }
  >,
  'getServiceQueue' : ActorMethod<[], Array<ServiceRecord>>,
  'getServiceRecord' : ActorMethod<[bigint], [] | [ServiceRecord]>,
  'getTransaction' : ActorMethod<[bigint], [] | [Transaction]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateInventoryItem' : ActorMethod<[InventoryItem], undefined>,
  'updateServiceStatus' : ActorMethod<
    [bigint, Status, [] | [string]],
    undefined
  >,
  'upsertCustomerRecord' : ActorMethod<[CustomerRecord], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];