/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InventoryItem = IDL.Record({
  'maxStock' : IDL.Nat,
  'sellPrice' : IDL.Nat,
  'minStock' : IDL.Nat,
  'stock' : IDL.Nat,
  'itemCode' : IDL.Text,
  'buyPrice' : IDL.Nat,
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Status = IDL.Variant({ 'masuk' : IDL.Null, 'selesai' : IDL.Null });
export const ServiceRecord = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : Status,
  'vehicleBrand' : IDL.Text,
  'technicianName' : IDL.Text,
  'repairAction' : IDL.Opt(IDL.Text),
  'vehicleModel' : IDL.Text,
  'plateNumber' : IDL.Opt(IDL.Text),
  'problemDescription' : IDL.Text,
});
export const TransactionItem = IDL.Record({
  'sellPrice' : IDL.Nat,
  'itemCode' : IDL.Text,
  'buyPrice' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'buyPrices' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(TransactionItem),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DiscountType = IDL.Variant({
  'goods' : IDL.Null,
  'services' : IDL.Null,
});
export const VehicleHistory = IDL.Record({
  'model' : IDL.Text,
  'brand' : IDL.Text,
  'plate' : IDL.Text,
});
export const CustomerRecord = IDL.Record({
  'discountAmount' : IDL.Nat,
  'name' : IDL.Text,
  'discountType' : DiscountType,
  'phone' : IDL.Text,
  'discountPercentage' : IDL.Nat,
  'vehicleHistory' : IDL.Vec(VehicleHistory),
  'transactionCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateInventoryItem' : IDL.Func([InventoryItem], [], []),
  'addServiceRecord' : IDL.Func([ServiceRecord], [IDL.Nat], []),
  'addTransaction' : IDL.Func([Transaction], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCustomerRecord' : IDL.Func([IDL.Text], [], []),
  'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
  'deleteServiceRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'findCustomersByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CustomerRecord)],
      ['query'],
    ),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerRecord)], ['query']),
  'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getAllServiceRecords' : IDL.Func([], [IDL.Vec(ServiceRecord)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CustomerRecord)],
      ['query'],
    ),
  'getInventoryItem' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(InventoryItem)],
      ['query'],
    ),
  'getProfitLossReport' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [
        IDL.Record({
          'grossProfit' : IDL.Nat,
          'totalCostOfGoodsSold' : IDL.Nat,
          'itemizedSales' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          'totalRevenue' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getServiceQueue' : IDL.Func([], [IDL.Vec(ServiceRecord)], ['query']),
  'getServiceRecord' : IDL.Func([IDL.Nat], [IDL.Opt(ServiceRecord)], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateServiceStatus' : IDL.Func(
      [IDL.Nat, Status, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'upsertCustomerRecord' : IDL.Func([CustomerRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InventoryItem = IDL.Record({
    'maxStock' : IDL.Nat,
    'sellPrice' : IDL.Nat,
    'minStock' : IDL.Nat,
    'stock' : IDL.Nat,
    'itemCode' : IDL.Text,
    'buyPrice' : IDL.Nat,
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const Status = IDL.Variant({ 'masuk' : IDL.Null, 'selesai' : IDL.Null });
  const ServiceRecord = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : Status,
    'vehicleBrand' : IDL.Text,
    'technicianName' : IDL.Text,
    'repairAction' : IDL.Opt(IDL.Text),
    'vehicleModel' : IDL.Text,
    'plateNumber' : IDL.Opt(IDL.Text),
    'problemDescription' : IDL.Text,
  });
  const TransactionItem = IDL.Record({
    'sellPrice' : IDL.Nat,
    'itemCode' : IDL.Text,
    'buyPrice' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'buyPrices' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(TransactionItem),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DiscountType = IDL.Variant({
    'goods' : IDL.Null,
    'services' : IDL.Null,
  });
  const VehicleHistory = IDL.Record({
    'model' : IDL.Text,
    'brand' : IDL.Text,
    'plate' : IDL.Text,
  });
  const CustomerRecord = IDL.Record({
    'discountAmount' : IDL.Nat,
    'name' : IDL.Text,
    'discountType' : DiscountType,
    'phone' : IDL.Text,
    'discountPercentage' : IDL.Nat,
    'vehicleHistory' : IDL.Vec(VehicleHistory),
    'transactionCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateInventoryItem' : IDL.Func([InventoryItem], [], []),
    'addServiceRecord' : IDL.Func([ServiceRecord], [IDL.Nat], []),
    'addTransaction' : IDL.Func([Transaction], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCustomerRecord' : IDL.Func([IDL.Text], [], []),
    'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
    'deleteServiceRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'findCustomersByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CustomerRecord)],
        ['query'],
      ),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerRecord)], ['query']),
    'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getAllServiceRecords' : IDL.Func([], [IDL.Vec(ServiceRecord)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomerRecord)],
        ['query'],
      ),
    'getInventoryItem' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(InventoryItem)],
        ['query'],
      ),
    'getProfitLossReport' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [
          IDL.Record({
            'grossProfit' : IDL.Nat,
            'totalCostOfGoodsSold' : IDL.Nat,
            'itemizedSales' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            'totalRevenue' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getServiceQueue' : IDL.Func([], [IDL.Vec(ServiceRecord)], ['query']),
    'getServiceRecord' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ServiceRecord)],
        ['query'],
      ),
    'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateServiceStatus' : IDL.Func(
        [IDL.Nat, Status, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'upsertCustomerRecord' : IDL.Func([CustomerRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };